# netlify.toml

# Configuración del proceso de construcción
[build]
  command = "npm run build" # El comando para construir tu proyecto
  publish = "build/client"  # Directorio con los assets estáticos (CSS, JS del cliente)
  functions = "build/server"# Directorio donde se encuentra la lógica del servidor (SSR)

# Redireccionamiento para que todo el tráfico pase por nuestra función SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200